import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/contexts/user/UserContext';
import { SurveyProvider } from '@/contexts/survey/SurveyContext';
import Navbar from '@/components/Navbar';
import SurveyFloatingButton from '@/components/survey/SurveyFloatingButton';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <SurveyProvider>
            <Navbar />
            {children}
            <SurveyFloatingButton />
            <Toaster position="top-right" />
          </SurveyProvider>
        </UserProvider>
      </body>
    </html>
  );
}
